name: Deploy
on:   [push]
env:
  IMAGE:              nginx-packed
  REGISTRY_HOSTNAME:  gcr.io
  GCP_ACCOUNT_ID:     ${{ secrets.GCP_ACCOUNT_ID }}
  GCP_KEY:            ${{ secrets.GCP_KEY }}
  GCP_PROJECT:        ${{ secrets.GCP_PROJECT }}
  GCP_REGION:         europe-west1
  GCP_ZONE:           europe-west1-b
jobs:
  Deploy:
    runs-on:    ubuntu-latest
    container:  gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    steps:

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

      - name: Install ytt
        run: |
          curl -Lo ytt https://github.com/vmware-tanzu/carvel-ytt/releases/download/v0.35.0/ytt-linux-amd64
          chmod +x ./ytt

      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure gcloud
        env:
        run: |
          echo $GCP_KEY | base64 -di > /tmp/gcp_key.json
          gcloud auth activate-service-account $GCP_ACCOUNT_ID --key-file=/tmp/gcp_key.json

          gcloud config set project $GCP_PROJECT
          gcloud config set compute/region $GCP_REGION
          gcloud config set compute/zone $GCP_ZONE

          gcloud container clusters get-credentials primary-cluster
          gcloud auth configure-docker $REGISTRY_HOSTNAME --quiet

      - name: Set Docker image name
        run: echo "::set-env name=DOCKER_TAG::$REGISTRY_HOSTNAME/$GCP_PROJECT/$IMAGE:${GITHUB_REF##*/}-${GITHUB_RUN_ID}"

      - name: Docker image build
        run: docker build -t $DOCKER_TAG .

      - name: Push image to GCR
        run: docker push $DOCKER_TAG

      - name: Create kube namespace
        run: |
          if ! kubectl get namespace "${GITHUB_REF##*/}"; then
            kubectl create namespace "${GITHUB_REF##*/}"
          fi

      - name: Kube templating and deploy
        run: |
          cat > values.yml <<EOF
          #@data/values
          ---
          image: $DOCKER_TAG
          EOF

          ./ytt -f nginx-pod.yml -f values.yml | kubectl --namespace "${GITHUB_REF##*/}" apply -f -